import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const ROOT = "C:/Users/shubham/OneDrive/Desktop/HOSPITAL MANGEMENT'";
const OUT = `${ROOT}/Hospital_Management_System_Updated_26_Slides.pptx`;
const BUILD = `${ROOT}/ppt_build`;
const W=1280,H=720;
const C={navy:'#0C2B4B',teal:'#07969B',aqua:'#DDF4F4',mist:'#F5F9FB',ink:'#162A3E',muted:'#66788A',line:'#D7E4EA',white:'#FFFFFF',gold:'#F5B942',green:'#2D936C'};
async function save(path,b){await fs.writeFile(path,new Uint8Array(await b.arrayBuffer()))}
function add(s,g,x,y,w,h,fill=C.white,line='none'){return s.shapes.add({geometry:g,position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:line,width:line==='none'?0:1},borderRadius:g==='roundRect'?'rounded-xl':undefined})}
function tx(s,v,x,y,w,h,fs=18,col=C.ink,bold=false,align='left'){const q=add(s,'textbox',x,y,w,h,'none');q.text=v;q.text.style={fontSize:fs,color:col,bold,alignment:align,fontFace:'Aptos'};return q}
function top(s,num,kicker,title,sub=''){tx(s,`CITY HOSPITAL  /  ${kicker.toUpperCase()}`,72,35,800,20,11,C.teal,true);tx(s,title,72,64,1050,50,34,C.navy,true);if(sub)tx(s,sub,72,116,1080,26,17,C.muted);add(s,'rect',72,155,1136,2,C.teal);tx(s,String(num).padStart(2,'0'),1155,35,53,20,12,C.muted,true,'right')}
function foot(s,n){add(s,'rect',72,667,1136,1,C.line);tx(s,'CITY HOSPITAL · HOSPITAL MANAGEMENT SYSTEM',72,680,460,17,10,C.muted,true);tx(s,`${n} / 26`,1130,680,78,17,10,C.muted,true,'right')}
function card(s,x,y,w,h,head,body,accent=C.teal){add(s,'roundRect',x,y,w,h,C.white,C.line);add(s,'rect',x,y,5,h,accent);tx(s,head,x+24,y+22,w-45,28,20,C.navy,true);tx(s,body,x+24,y+62,w-45,h-78,16,C.muted)}
function dot(s,x,y,c=C.teal){add(s,'ellipse',x,y,12,12,c)}
async function imgBytes(f){const b=await fs.readFile(f);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}
function image(s,blob,x,y,w,h,fit='cover'){s.images.add({blob,contentType:'image/png',alt:'City Hospital website screenshot',fit,position:{left:x,top:y,width:w,height:h},geometry:'roundRect',borderRadius:'rounded-xl'})}
function pill(s,label,x,y,w){add(s,'roundRect',x,y,w,38,C.aqua,'none');tx(s,label,x+8,y+10,w-16,18,14,C.navy,true,'center')}

async function main(){
 const home=await imgBytes(`${BUILD}/website-home.png`), doctors=await imgBytes(`${BUILD}/website-doctors.png`), login=await imgBytes(`${BUILD}/website-login.png`);
 const p=Presentation.create({slideSize:{width:W,height:H}}); const slide=()=>{const s=p.slides.add();s.background.fill=C.white;return s};
 // 1
 {const s=slide();add(s,'rect',0,0,24,H,C.teal);add(s,'roundRect',776,107,354,400,C.aqua);add(s,'ellipse',857,177,192,192,C.white,C.teal);tx(s,'+',870,183,166,155,120,C.teal,false,'center');tx(s,'CITY HOSPITAL',76,120,420,25,17,C.teal,true);tx(s,'Hospital\nManagement\nSystem',72,170,610,210,56,C.navy,true);tx(s,'A complete web platform for patient care, clinical coordination and hospital operations.',76,430,570,60,21,C.muted);pill(s,'PROJECT PRESENTATION',76,550,220);tx(s,'2026 · Team Presentation',76,606,370,24,16,C.ink,true);}
 //2
 {const s=slide();top(s,2,'Introduction','Transforming hospital workflows into a connected digital experience','A unified system reduces manual coordination while keeping every role focused on its own tasks.');card(s,72,210,335,247,'The challenge','Appointments, records, doctor schedules and billing are often maintained across disconnected manual processes.');card(s,472,210,335,247,'The solution','City Hospital combines patient, doctor and administrator workflows in one browser-based application.',C.gold);card(s,872,210,336,247,'The outcome','A transparent journey from registration to appointment, prescription, payment and bill download.',C.green);foot(s,2)}
 //3
 {const s=slide();top(s,3,'Vision','What this project delivers','The platform brings three audiences together through one shared data foundation.');const data=[['Patients','Discover doctors, register securely, book visits and review medical activity.'],['Doctors','Access assigned appointments, update professional information and manage prescriptions.'],['Administrators','Maintain hospital data, oversee appointments and generate bills.']];data.forEach((r,i)=>{const x=72+i*382;add(s,'roundRect',x,215,334,265,i===1?C.aqua:C.mist,C.line);tx(s,`0${i+1}`,x+26,240,70,22,16,C.teal,true);tx(s,r[0],x+26,296,260,34,25,C.navy,true);tx(s,r[1],x+26,352,270,76,17,C.muted)});foot(s,3)}
 //4
 {const s=slide();top(s,4,'Team','Team information & contribution map','Replace names below before your viva or final submission.');const t=[['Team Member 1','Frontend implementation','HTML · CSS · JavaScript'],['Team Member 2','Backend implementation','Node.js · Express APIs'],['Team Member 3','Database integration','MySQL · SQL schema'],['Team Member 4','Testing & documentation','QA · PPT · presentation']];t.forEach((r,i)=>{const x=72+(i%2)*568,y=205+Math.floor(i/2)*160;add(s,'roundRect',x,y,528,122,C.mist,C.line);add(s,'ellipse',x+26,y+29,64,64,C.aqua,C.teal);tx(s,`T${i+1}`,x+26,y+48,64,20,16,C.teal,true,'center');tx(s,r[0],x+116,y+24,260,27,22,C.navy,true);tx(s,r[1],x+116,y+60,270,24,17,C.ink,true);tx(s,r[2],x+116,y+88,280,18,15,C.muted)});foot(s,4)}
 //5
 {const s=slide();top(s,5,'Architecture','A simple three-tier architecture keeps responsibilities clear','The browser, API and database layers communicate through explicit interfaces.');add(s,'rect',305,348,180,3,C.line);add(s,'rect',574,348,180,3,C.line);add(s,'rect',843,348,180,3,C.line);[['Frontend','HTML / CSS / JavaScript'],['Backend','Node.js / Express'],['Database','MySQL'],['Output','JSON / PDF Bill']].forEach((r,i)=>{const x=72+i*269;add(s,'roundRect',x,270,215,158,i===2?C.aqua:C.mist,C.line);tx(s,`0${i+1}`,x+18,292,60,20,14,C.teal,true);tx(s,r[0],x+18,332,180,27,22,C.navy,true,'center');tx(s,r[1],x+16,373,184,34,15,C.muted,false,'center')});tx(s,'Each layer has one job: present the experience, enforce business rules, persist data, and return useful results.',135,520,1010,32,21,C.ink,false,'center');foot(s,5)}
 //6
 {const s=slide();top(s,6,'Website experience','The homepage introduces services and directs users to the right action','A clear header, booking CTA, departments and doctor listing form the first-touch experience.');add(s,'roundRect',72,184,766,431,C.mist,C.line);image(s,home,86,198,738,403);card(s,887,210,270,114,'Hero section','Trusted healthcare message and immediate booking action.');card(s,887,348,270,114,'Navigation','Home, doctors, booking, login and patient registration.',C.gold);card(s,887,486,270,114,'Live data','Departments and doctors are rendered from API results.',C.green);foot(s,6)}
 //7
 {const s=slide();top(s,7,'Frontend','Frontend technology stack','The interface is intentionally lightweight, responsive and built without a heavy framework.');[['HTML5','Semantic page structure for home, login, registration and dashboards.'],['CSS3','Shared styling for layout, forms, cards, modals, navigation and responsive views.'],['JavaScript','DOM rendering, API calls, session handling, validation and dynamic navigation.']].forEach((r,i)=>card(s,72+i*382,210,334,236,r[0],r[1],i===1?C.gold:C.teal));pill(s,'CLIENT-SIDE RENDERING',72,515,220);pill(s,'FETCH API',316,515,148);pill(s,'LOCAL STORAGE',488,515,184);foot(s,7)}
 //8
 {const s=slide();top(s,8,'Frontend','Doctor discovery and appointment booking','The doctor directory receives data from the backend and guides a patient into the booking flow.');add(s,'roundRect',72,184,660,430,C.mist,C.line);image(s,doctors,86,198,632,402);card(s,790,205,365,96,'1. Browse doctors','Specializations and department data are displayed from the API.');card(s,790,322,365,96,'2. Choose a slot','Patients select a doctor, date and time using the booking interface.',C.gold);card(s,790,439,365,96,'3. Confirm appointment','The request is sent to the backend for validation and persistence.',C.green);foot(s,8)}
 //9
 {const s=slide();top(s,9,'Frontend','Authentication creates role-based journeys','Login captures user credentials and the interface redirects each role to its own dashboard.');add(s,'roundRect',72,184,600,431,C.mist,C.line);image(s,login,86,198,572,403);const r=[['Admin','Manages hospital data and operational overview'],['Doctor','Views appointments and maintains profile'],['Patient','Books appointments and checks personal history']];r.forEach((v,i)=>{const y=208+i*112;add(s,'roundRect',746,y,413,86,i===1?C.aqua:C.mist,C.line);tx(s,v[0],772,y+22,110,25,20,C.navy,true);tx(s,v[1],897,y+20,230,46,16,C.muted)});foot(s,9)}
 //10
 {const s=slide();top(s,10,'Frontend','Client-side logic connects screens to the API','JavaScript keeps the UI interactive while REST endpoints remain the source of truth.');const flows=[['Fetch & render','Departments and doctors load into page sections and select controls.'],['Form submission','Registration, login and appointment forms send structured JSON payloads.'],['Session awareness','Local storage holds the active role and updates navigation accordingly.'],['Feedback','Success, validation and error messages give users immediate guidance.']];flows.forEach((r,i)=>{const x=72+(i%2)*568,y=205+Math.floor(i/2)*170;card(s,x,y,528,125,r[0],r[1],i===1?C.gold:C.teal)});foot(s,10)}
 //11
 {const s=slide();top(s,11,'Backend','Express is the application’s service layer','The server exposes focused routes that validate inputs, query MySQL and respond with JSON.');add(s,'roundRect',72,205,300,300,C.navy,'none');tx(s,'Express\nServer',108,286,225,80,35,C.white,true,'center');tx(s,'Port 5001',108,382,225,24,16,C.aqua,true,'center');[['Route layer','Maps URLs and HTTP methods to hospital actions'],['Validation layer','Checks required values, IDs, formats and allowed statuses'],['Data layer','Runs parameterized mysql2 queries and handles errors']].forEach((r,i)=>{const y=205+i*104;add(s,'roundRect',444,y,670,82,C.mist,C.line);tx(s,r[0],472,y+20,180,24,19,C.navy,true);tx(s,r[1],672,y+19,408,38,16,C.muted)});foot(s,11)}
 //12
 {const s=slide();top(s,12,'Backend','REST API coverage maps directly to system features','Clear endpoints make the frontend predictable and keep backend behavior modular.');const a=[['GET','/api/departments','List hospital departments'],['GET','/api/doctors','List doctors with department details'],['POST','/api/patients','Register a new patient account'],['POST','/api/appointments','Create a validated appointment'],['PUT','/api/appointments/:id/status','Update appointment status'],['POST / PUT','/api/appointments/:id/prescription','Create or update clinical prescription'],['POST','/api/appointments/:id/bill','Generate appointment bill'],['GET','/api/bills/:id/pdf','Download formatted bill PDF']];a.forEach((r,i)=>{const x=72+(i%2)*568,y=180+Math.floor(i/2)*100;add(s,'roundRect',x,y,528,68,C.mist,C.line);tx(s,r[0],x+18,y+22,122,18,14,C.teal,true);tx(s,r[1],x+148,y+15,254,20,15,C.ink,true);tx(s,r[2],x+148,y+38,310,17,13,C.muted)});foot(s,12)}
 //13
 {const s=slide();top(s,13,'Backend','Business rules protect data quality before a query runs','The backend blocks malformed, incomplete and conflicting requests before database changes happen.');const rules=[['Required fields','Names, credentials and mandatory clinical data cannot be empty.'],['Format checks','IDs must be positive; appointment dates and times use expected formats.'],['Status control','Appointments accept only Pending, Confirmed or Cancelled.'],['Duplicate prevention','The same doctor cannot be actively booked in the same time slot.'],['One-per-visit records','One prescription and one bill are allowed per appointment.']];rules.forEach((r,i)=>{const y=186+i*78;dot(s,86,y+21,i===3?C.gold:C.teal);tx(s,r[0],116,y+10,260,23,19,C.navy,true);tx(s,r[1],410,y+10,705,39,16,C.muted)});foot(s,13)}
 //14
 {const s=slide();top(s,14,'Database','MySQL provides the shared source of truth','Relational tables ensure every workflow has a reliable, connected record.');const db=[['admins','Admin credentials'],['departments','Hospital department and location'],['doctors','Profile, specialization, department and login'],['patients','Personal, health and emergency information'],['appointments','Patient–doctor schedule and status'],['prescriptions','Diagnosis, medicines and instructions'],['bills','Amount, payment status and billing date']];db.forEach((r,i)=>{const x=72+(i%2)*568,y=180+Math.floor(i/2)*75;add(s,'roundRect',x,y,528,54,i===2?C.aqua:C.mist,C.line);tx(s,r[0],x+22,y+16,178,21,17,C.navy,true);tx(s,r[1],x+218,y+16,280,21,15,C.muted)});foot(s,14)}
 //15
 {const s=slide();top(s,15,'Database','Relationships preserve the clinical journey','Foreign keys connect records while unique constraints prevent duplicate visit details.');add(s,'rect',345,286,130,3,C.line);add(s,'rect',635,286,130,3,C.line);add(s,'rect',925,286,130,3,C.line);[['Patients','patient_id'],['Appointments','patient_id · doctor_id'],['Prescriptions','appointment_id UNIQUE'],['Bills','appointment_id UNIQUE']].forEach((r,i)=>{const x=72+i*290;add(s,'roundRect',x,226,236,122,i===1?C.aqua:C.mist,C.line);tx(s,r[0],x+14,254,208,26,21,C.navy,true,'center');tx(s,r[1],x+14,296,208,21,14,C.muted,true,'center')});add(s,'roundRect',158,448,964,82,C.mist,C.line);tx(s,'Department → Doctor relationship: every doctor references one department, enabling joined doctor-directory results.',194,475,890,27,19,C.ink,true,'center');foot(s,15)}
 //16
 {const s=slide();top(s,16,'Integration','End-to-end appointment creation in four dependable steps','This is the key integration point between frontend interaction, backend rules and MySQL.');add(s,'rect',293,336,185,3,C.line);add(s,'rect',569,336,185,3,C.line);add(s,'rect',845,336,185,3,C.line);[['Patient UI','Select doctor, date and time'],['Express API','Validate request payload'],['MySQL check','Detect active slot conflicts'],['Confirmed result','Insert appointment & return JSON']].forEach((r,i)=>{const x=72+i*276;add(s,'roundRect',x,260,222,152,i===2?C.aqua:C.mist,C.line);tx(s,`0${i+1}`,x+18,280,45,19,14,C.teal,true);tx(s,r[0],x+18,319,185,27,20,C.navy,true,'center');tx(s,r[1],x+18,360,185,30,15,C.muted,false,'center')});tx(s,'Conflict response: if an existing non-cancelled appointment uses the same doctor, date and time, the API returns HTTP 409.',130,505,1025,30,18,C.teal,true,'center');foot(s,16)}
 //17
 {const s=slide();top(s,17,'Integration','From consultation to prescription and bill','Medical and payment records remain tied to the original appointment.');const journey=[['Appointment','Patient meets assigned doctor'],['Prescription','Doctor saves diagnosis, medicines and instructions'],['Billing','Admin creates amount and payment status'],['PDF Output','System formats a downloadable City Hospital bill']];journey.forEach((r,i)=>{const x=72+(i%2)*568,y=205+Math.floor(i/2)*165;card(s,x,y,528,120,r[0],r[1],i===2?C.gold:C.teal)});foot(s,17)}
 //18
 {const s=slide();top(s,18,'Security & quality','Current safeguards and future hardening','The implementation includes validation and parameterized SQL, with a clear roadmap for production readiness.');card(s,72,205,508,285,'Implemented safeguards','• Server-side validation for fields, formats and status values\n• mysql2 placeholder queries for query parameters\n• Duplicate appointment, bill and prescription handling\n• Database error responses for failed requests',C.green);card(s,700,205,508,285,'Recommended next steps','• Password hashing and secure session tokens\n• Role-based authorization middleware\n• HTTPS, rate limiting and audit logs\n• Automated API and UI test coverage',C.gold);foot(s,18)}
 //19
 {const s=slide();top(s,19,'Value','Why City Hospital is a strong full-stack project','It demonstrates a complete feature flow—not only interface pages or database tables.');[['Full-stack delivery','Frontend, backend and MySQL work as one application.'],['Real-world roles','Patient, doctor and administrator journeys reflect hospital operations.'],['Relational design','Tables and constraints make records dependable and traceable.'],['Extendable base','Notifications, reports, payments and analytics can be added next.']].forEach((r,i)=>{const x=72+(i%2)*568,y=200+Math.floor(i/2)*160;card(s,x,y,528,118,r[0],r[1],i===1?C.gold:C.teal)});foot(s,19)}
 //20
 {const s=slide();top(s,20,'Backend deep dive','How an Express request becomes a database response','Every operation follows the same controlled path from client request to response payload.');
  add(s,'rect',280,331,174,3,C.line);add(s,'rect',543,331,174,3,C.line);add(s,'rect',806,331,174,3,C.line);
  [['HTTP request','POST /api/appointments'],['Route handler','Read req.params and req.body'],['Validation','Check fields and rules'],['SQL query','Parameterized mysql2 call']].forEach((r,i)=>{const x=72+i*263;add(s,'roundRect',x,254,212,155,i===2?C.aqua:C.mist,C.line);tx(s,`0${i+1}`,x+18,276,44,18,13,C.teal,true);tx(s,r[0],x+16,317,180,25,19,C.navy,true,'center');tx(s,r[1],x+18,357,176,30,14,C.muted,false,'center')});
  add(s,'roundRect',270,488,740,62,C.navy,'none');tx(s,'JSON response → frontend updates the screen with success, validation, or conflict feedback.',302,507,676,24,18,C.white,true,'center');foot(s,20)}
 //21
 {const s=slide();top(s,21,'Backend deep dive','Route examples show a clean API design','Endpoints are grouped around hospital resources and use the right HTTP method for each action.');
  const r=[['GET','/api/doctors/:id','Return one doctor profile with department details'],['PUT','/api/doctors/:id/profile','Update doctor name, specialization and phone'],['GET','/api/doctor/:id/summary','Return appointment totals by status'],['POST','/api/appointments/:id/prescription','Store clinical prescription for one appointment'],['POST','/api/appointments/:id/bill','Create bill with payment status'],['GET','/api/bills/:id/pdf','Generate and download patient bill']];
  r.forEach((v,i)=>{const x=72+(i%2)*568,y=186+Math.floor(i/2)*112;add(s,'roundRect',x,y,528,80,C.mist,C.line);tx(s,v[0],x+20,y+18,106,19,15,C.teal,true);tx(s,v[1],x+145,y+15,350,20,15,C.navy,true);tx(s,v[2],x+145,y+42,350,20,14,C.muted)});foot(s,21)}
 //22
 {const s=slide();top(s,22,'Backend deep dive','Error handling keeps API feedback useful and predictable','The server distinguishes invalid input, missing records, conflicts and database failures.');
  const e=[['400 · Bad Request','Invalid ID, missing field, invalid date/time or unsupported status'],['401 · Unauthorized','Login credentials do not match an existing user'],['404 · Not Found','Requested doctor, patient, appointment, bill or prescription is missing'],['409 · Conflict','Doctor time slot, prescription or bill already exists'],['500 · Server Error','Database operation fails and a safe error response is returned']];
  e.forEach((v,i)=>{const y=180+i*76;add(s,'roundRect',72,y,1136,57,i===3?C.aqua:C.mist,C.line);tx(s,v[0],98,y+17,255,21,17,C.navy,true);tx(s,v[1],390,y+17,770,21,15,C.muted)});foot(s,22)}
 //23
 {const s=slide();top(s,23,'Database deep dive','Core table design supports every hospital transaction','Primary keys identify records; foreign keys connect each workflow safely.');
  const tabs=[['patients','patient_id (PK)','Profile, health data, emergency contact'],['doctors','doctor_id (PK)','Specialization, phone, department_id (FK)'],['appointments','appointment_id (PK)','patient_id (FK), doctor_id (FK), status'],['prescriptions','prescription_id (PK)','appointment_id (FK, UNIQUE), diagnosis'],['bills','bill_id (PK)','appointment_id (FK, UNIQUE), amount, payment']];
  tabs.forEach((v,i)=>{const y=178+i*78;add(s,'roundRect',72,y,1136,58,i===2?C.aqua:C.mist,C.line);tx(s,v[0],96,y+18,210,20,17,C.navy,true);tx(s,v[1],330,y+18,265,20,15,C.teal,true);tx(s,v[2],620,y+18,530,20,15,C.muted)});foot(s,23)}
 //24
 {const s=slide();top(s,24,'Database deep dive','SQL joins build complete, role-ready views','The backend combines related tables instead of returning isolated records.');
  add(s,'roundRect',72,190,526,294,C.navy,'none');tx(s,'Appointment listing joins',102,220,390,28,23,C.white,true);tx(s,'appointments\n  JOIN patients\n  JOIN doctors\n  LEFT JOIN bills',114,278,320,112,19,C.aqua,true);tx(s,'Returns: patient name, doctor name, date, time, status and billing data.',102,415,410,42,16,C.white);
  add(s,'roundRect',682,190,526,294,C.mist,C.line);tx(s,'Patient history joins',712,220,390,28,23,C.navy,true);tx(s,'appointments\n  JOIN doctors\n  LEFT JOIN prescriptions\n  LEFT JOIN bills',724,278,340,112,19,C.teal,true);tx(s,'Returns: upcoming visits, diagnosis, medicines, bill and payment status.',712,415,420,42,16,C.muted);
  tx(s,'LEFT JOIN preserves appointments even when a bill or prescription has not been created yet.',112,548,1056,26,19,C.teal,true,'center');foot(s,24)}
 //25
 {const s=slide();top(s,25,'Database deep dive','Integrity constraints prevent duplicate clinical records','The schema makes key hospital rules enforceable at database level.');
  const c=[['AUTO_INCREMENT primary keys','Every record receives a unique ID automatically.'],['Foreign keys','Appointments reference valid patients and doctors.'],['UNIQUE appointment_id','One prescription and one bill can exist per appointment.'],['ON DELETE CASCADE','Related prescription and bill records are removed with a deleted appointment.'],['DECIMAL(10,2)','Bill amounts retain accurate currency precision.']];
  c.forEach((v,i)=>{const x=72+(i%2)*568,y=182+Math.floor(i/2)*125;add(s,'roundRect',x,y,528,96,i===4?C.aqua:C.mist,C.line);tx(s,v[0],x+25,y+19,450,24,19,C.navy,true);tx(s,v[1],x+25,y+53,460,24,15,C.muted)});foot(s,25)}
 //27 final, then page denominator is corrected below
 {const s=slide();add(s,'rect',0,0,24,H,C.teal);tx(s,'CITY HOSPITAL',76,132,310,24,17,C.teal,true);tx(s,'A connected foundation\nfor better hospital\nmanagement.',72,190,650,175,48,C.navy,true);tx(s,'Thank you',76,430,300,45,34,C.navy,true);tx(s,'Questions & discussion',78,482,360,28,20,C.muted);add(s,'roundRect',794,155,316,316,C.aqua);add(s,'ellipse',866,218,172,172,C.white,C.teal);tx(s,'+',882,221,140,140,108,C.teal,false,'center');tx(s,'Hospital Management System',794,520,316,24,16,C.teal,true,'center');foot(s,26)}
 for(const [i,s] of p.slides.items.entries())await save(`${BUILD}/premium-slide-${String(i+1).padStart(2,'0')}.png`,await p.export({slide:s,format:'png',scale:1}));
 await save(`${BUILD}/premium-montage.webp`,await p.export({format:'webp',montage:true,scale:1}));const out=await PresentationFile.exportPptx(p);await out.save(OUT);
}
main().catch(e=>{console.error(e);process.exitCode=1});
